version: '3.8'
services:
  core:
    container_name: ml-pipe-core
    build:
      context: .
      dockerfile: Dockerfile.core
    restart: always
    command: ["fastapi", "dev", "./main.py", "--host", "0.0.0.0", "--port", "80"]
    platform: linux/amd64
    ports: 
      - "8000:80"
    volumes:
      - ./data:/app/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
  sci-trainer:
    container_name: ml-pipe-sci-trainer
    build:
      context: .
      dockerfile: Dockerfile.sci-trainer
    restart: always
    command: ["fastapi", "dev", "./main.py", "--host", "0.0.0.0", "--port", "80"]
    platform: linux/amd64
    ports: 
      - "8001:80"
    volumes:
      - ./data:/app/data
    extra_hosts:
      - "host.docker.internal:host-gateway"

